### ISSUE TITLE
key office 2021

### ISSUE THREAD

**Issue by ahmedfathy221** [tylerdotrar/Activate-MicrosoftOffice#1]
key office 2021

**Comment by tylerdotrar** [comment]
Could you elaborate on your issue?
- What version of Windows are you using? (*e.g., Windows 10 Pro, Windows 11 Home, etc.*)
- Is your system *32-bit* or *64-bit*?
- What error message did the script return?

**Comment by Hermansonelyte** [comment]
I got the Office 2021 Pro Plus key from the Microsoft partner store keyingo.com, it is working good !

**Comment by tylerdotrar** [comment]
I have tested this on the latest Windows 11 24H2 image, using the official Microsoft Office 2021 download listed in the README. No issues occurred, and no extra keys were required.
